"""
Django settings for micuenta project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from decouple import config


SECRET_KEY = 'django-insecure-9e)!h0&q!7cfhcpn6m3&y@!2r8$b#u8zaf)%$uygw-)a)!*^fg'


DEBUG = True

ALLOWED_HOSTS = ['localhost','192.168.2.185']


INSTALLED_APPS = [
     
    #'admin_tools_stats',      # django-admin-charts
    #'django_nvd3',            # dependencia para gráficos

     # Herramientas de admin-tools (menu, theming, dashboard)
    #'admin_tools',
    #'admin_tools.theming',
    #'admin_tools.menu',
    #'admin_tools.dashboard',

    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'micuenta',
    'gestion_supervisor',
    'gestion_usuarios',
    'gestion_ia',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'micuenta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'loaders': [
                'admin_tools.template_loaders.Loader',           # para admin_tools
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'micuenta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'es' #estaba en en-us
TIME_ZONE = 'America/Bogota' ##'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {

   "custom_css": "css/admin_override.css",
    "site_title": "Mi Cuenta - SECOPS",
    "site_header": "Mi Panel de Admin",
    "site_brand": "SECOPS ",
    "welcome_sign": " @d4n7.dev© SECOPS E.S.E IMSALUD V0.0",
    "copyright": "/ @d4n7.dev SECOPS E.S.E IMSALUD V0.0",
    "show_ui_builder": False,
    "show_jazzmin_version": True,
   
    "user_icon": "fas fa-user-circle", 
    
    # Personalización de colores y tema
    "site_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    
    # Personalización del menú
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["gestion_usuarios", "gestion_supervisor", "micuenta", "gestion_ia", "auth"],


    "icons": {
        # Aplicaciones personalizadas
        "gestion_supervisor": "fas fa-user-shield",
        "gestion_supervisor.supervisor": "fas fa-user-tie",  
        
        # Micuenta
        "micuenta": "fas fa-cogs",
        "micuenta.dependencia": "fas fa-building",
        "micuenta.radicado": "fas fa-file-alt",
        "micuenta.cuentabancaria": "fas fa-university",
        
        # Gestion Usuarios
        "gestion_usuarios": "fas fa-users",
        "gestion_usuarios.usuario": "fas fa-user-cog",
        "gestion_usuarios.contrato": "fas fa-file-contract",
        "gestion_usuarios.rp": "fas fa-file-invoice-dollar",
        "gestion_usuarios.actainicio": "fas fa-file-signature",
        "gestion_usuarios.planilla": "fas fa-clipboard-list",
        "gestion_usuarios.documento": "fas fa-file-pdf",
        
        # Gestion IA
        "gestion_ia": "fas fa-robot",
        
        # Default
        "admin": "fas fa-shield-alt",
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",

        "admin.LogEntry": "fas fa-file-alt",
        "auth.Permission": "fas fa-key",
        "contenttypes.ContentType": "fas fa-database",
        "sessions.Session": "fas fa-clock",
        "sites.Site": "fas fa-globe",
    
    },

    
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": True,
    "accent": "accent-success",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-outline-success",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    },
    "brand_colour": False,
}

###CONFIGURACION DE CORREO
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = config('EMAIL_HOST')
#EMAIL_PORT = config('EMAIL_PORT', cast=int)
#EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
#EMAIL_HOST_USER = config('EMAIL_HOST_USER')
#EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
#DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')