# Generated by Django 5.2.3 on 2025-06-25 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_supervisor', '0001_initial'),
        ('micuenta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('nombre', models.CharField(max_length=40, verbose_name='Primer nombre')),
                ('segundonombre', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo nombre')),
                ('primerapellido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Primer apellido')),
                ('segundoapellido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo apellido')),
                ('cargo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=40, null=True, verbose_name='Correo personal')),
                ('tipodocumento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('PP', 'Pasaporte'), ('CE', 'Cedula de extranjeria'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('PEP', 'Permiso especial de permanencia')], default='CC', max_length=40, verbose_name='Tipo de documento')),
                ('cedula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('lugarexpedicion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Lugar de expedicion')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('I', 'Indefenido')], default='F', max_length=40, verbose_name='Sexo')),
                ('telefono', models.BigIntegerField(blank=True, null=True, verbose_name='Telefono fijo')),
                ('celular', models.BigIntegerField(blank=True, null=True, verbose_name='Celular')),
                ('direccion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Direccion completa')),
                ('rol', models.CharField(choices=[('admin_identidadades', 'Administrador de identidades'), ('supervisor', 'Supervisor'), ('identidades', 'Usuario final de identidades'), ('informes', 'Ente de control (informes)'), ('admin_sara', 'Administrador de SARA'), ('paciente', 'Paciente')], default='identidades', max_length=40, verbose_name='Rol')),
                ('fechafinalcontrato', models.DateField(blank=True, null=True, verbose_name='Fecha final del contrato')),
                ('imagen', models.ImageField(default='imgs/sinfoto.jpeg', upload_to='imgs/')),
                ('dependencia', models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='micuenta.dependencia', verbose_name='dependencia')),
                ('supervisor', models.ForeignKey(default=1, max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_detail', to='gestion_supervisor.supervisor', verbose_name='supervisor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario autenticado')),
            ],
        ),
    ]
