# Generated by Django 5.2.3 on 2025-06-25 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0001_initial'),
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_micuenta', 'Administrador de cuentas')], default='identidades', max_length=40, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número')),
                ('numeroproceso', models.IntegerField(verbose_name='Número del proceso')),
                ('objeto', models.CharField(max_length=300, verbose_name='Objeto del contrato')),
                ('fechaperfeccionamiento', models.DateField(verbose_name='Fecha de perfeccionamiento')),
                ('valor', models.BigIntegerField(verbose_name='Valor del contrato')),
                ('fechacontrato', models.DateField(verbose_name='Fecha inicial del contrato')),
                ('fechaterminacion', models.DateField(verbose_name='Fecha final del contrato')),
                ('duracion_meses', models.IntegerField(default=0, verbose_name='Duración (meses)')),
                ('duracion_dias', models.IntegerField(default=0, verbose_name='Duración (días)')),
                ('archivo', models.FileField(upload_to='pdfs/', verbose_name='Archivo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_supervisor.supervisor', verbose_name='Supervisor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario')),
            ],
        ),
    ]
