# Generated by Django 5.2.5 on 2025-08-17 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_usuario_rol_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='rp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rp', models.CharField(max_length=50, unique=True, verbose_name='Número de RP')),
                ('numero_contrato', models.CharField(max_length=50, verbose_name='Número de Contrato')),
                ('tipo_contrato', models.CharField(max_length=100, verbose_name='Tipo de Contrato')),
                ('duracion', models.CharField(max_length=100, verbose_name='Duración')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha Final')),
                ('objeto', models.TextField(verbose_name='Objeto del Contrato')),
                ('fecha_rp', models.DateField(verbose_name='Fecha de RP')),
                ('fecha_suscripcion', models.DateField(verbose_name='Fecha de Suscripción')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='rp/', verbose_name='Archivo Adjunto')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='firma',
            field=models.ImageField(default='imgs/sinfoto.jpeg', upload_to='imgs/firmas'),
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(upload_to='documentos/', verbose_name='Archivo adjunto')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario', verbose_name='Usuario asociado')),
            ],
        ),
        migrations.CreateModel(
            name='planilla',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de la planilla')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago de la planilla')),
                ('periodo', models.CharField(choices=[('01', 'ENERO'), ('02', 'FEBRERO'), ('03', 'MARZO'), ('04', 'ABRIL'), ('05', 'MAYO'), ('06', 'JUNIO'), ('07', 'JULIO'), ('08', 'AGOSTO'), ('09', 'SEPTIEMBRE'), ('10', 'OCTUBRE'), ('11', 'NOVIEMBRE'), ('12', 'DICIEMBRE')], max_length=2, verbose_name='Mes de pago')),
                ('ibc', models.CharField(max_length=200, verbose_name='IBC de la planilla')),
                ('nombre_pension', models.CharField(max_length=150, verbose_name='Entidad de pensión')),
                ('valor_pension', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de pensión')),
                ('nombre_salud', models.CharField(max_length=150, verbose_name='Entidad de salud')),
                ('valor_salud', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de salud')),
                ('nombre_arl', models.CharField(max_length=150, verbose_name='Entidad ARL')),
                ('valor_arl', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de ARL')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total de la planilla')),
                ('archivo', models.FileField(default='NO CARGADO', upload_to='pdfs/', verbose_name='Archivo de soporte')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario', verbose_name='Usuario asociado')),
            ],
        ),
        migrations.DeleteModel(
            name='contrato',
        ),
    ]
