# Generated by Django 5.2.3 on 2025-07-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_usuario_rol_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='duracion_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración (días)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor del contrato'),
        ),
    ]
