# Generated by Django 5.2.3 on 2025-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_alter_contrato_duracion_dias_alter_contrato_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='duracion_meses',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Duración (meses)'),
        ),
    ]
