# Generated by Django 5.2.5 on 2025-08-17 00:40

from django.db import migrations


def add_numero_rp_column(apps, schema_editor):
    """Agregar columna numero_rp si no existe"""
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna numero_rp existe
        cursor.execute("PRAGMA table_info(gestion_usuarios_rp)")
        columns = [row[1] for row in cursor.fetchall()]
        
        if 'numero_rp' not in columns:
            try:
                cursor.execute("ALTER TABLE gestion_usuarios_rp ADD COLUMN numero_rp VARCHAR(50)")
                print("Columna numero_rp agregada exitosamente")
            except Exception as e:
                print(f"Error agregando columna numero_rp: {e}")
        else:
            print("La columna numero_rp ya existe")


def reverse_add_numero_rp_column(apps, schema_editor):
    """Función de reversa - no hacer nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_auto_20250816_1940'),
    ]

    operations = [
        migrations.RunPython(add_numero_rp_column, reverse_add_numero_rp_column),
    ]
