# Generated by Django 5.2.3 on 2025-07-06 13:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_alter_contrato_duracion_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 6, 13, 41, 9, 466498, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='rp',
            fields=[
                ('numero', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Numero del rp')),
                ('fecha', models.DateField(max_length=300, verbose_name='Fecha del rp')),
                ('archivo', models.FileField(default='No cargado', upload_to='pdfs/', verbose_name='archivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario')),
            ],
        ),
    ]
