# Generated by Django 5.2.5 on 2025-08-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0005_contrato_fecha_actualizacion_contrato_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='actainicio',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero del proceso')),
                ('fecha', models.CharField(max_length=300, verbose_name='Fecha de acta de inicio')),
                ('archivo', models.FileField(default='NO CARGADO', upload_to='pdfs/', verbose_name='archivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario')),
            ],
        ),
    ]
