# Generated by Django 5.2.5 on 2025-08-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0006_actainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actainicio',
            name='numero',
        ),
        migrations.AddField(
            model_name='actainicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='actainicio',
            name='fecha',
            field=models.DateField(max_length=300, verbose_name='Fecha del rp'),
        ),
    ]
