# Generated by Django 5.2.5 on 2025-08-17 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0001_initial'),
        ('gestion_usuarios', '0006_auto_20250816_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagos', models.IntegerField(verbose_name='Número de pagos')),
                ('numero_proceso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de proceso (opcional)')),
                ('archivo', models.FileField(upload_to='contratos/', verbose_name='Archivo adjunto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('supervisor', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='gestion_supervisor.supervisor', verbose_name='supervisor')),
            ],
        ),
    ]
