# Generated by Django 5.2.5 on 2025-08-17 01:28

from django.db import migrations, models
import django.db.models.deletion


def recreate_contrato_table(apps, schema_editor):
    """
    Elimina la tabla existente gestion_usuarios_contrato y la recrea con la estructura correcta
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Eliminar la tabla existente
        cursor.execute("DROP TABLE IF EXISTS gestion_usuarios_contrato")
        
        # Crear la nueva tabla con la estructura correcta
        cursor.execute("""
            CREATE TABLE "gestion_usuarios_contrato" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "numero_pagos" integer NOT NULL,
                "supervisor_id" bigint NOT NULL REFERENCES "gestion_usuarios_supervisor" ("id") DEFERRABLE INITIALLY DEFERRED,
                "numero_proceso" varchar(100),
                "archivo" varchar(100) NOT NULL,
                "fecha_creacion" datetime NOT NULL,
                "fecha_actualizacion" datetime NOT NULL
            )
        """)
        
        # Crear índice para la clave foránea
        cursor.execute("""
            CREATE INDEX "gestion_usuarios_contrato_supervisor_id_idx" 
            ON "gestion_usuarios_contrato" ("supervisor_id")
        """)


def reverse_recreate_contrato_table(apps, schema_editor):
    """
    Función de reversión - no implementada ya que no podemos recuperar los datos originales
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0007_contrato'),
    ]

    operations = [
        migrations.RunPython(
            recreate_contrato_table,
            reverse_recreate_contrato_table,
        ),
    ]
