# Generated by Django 5.2.5 on 2025-08-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0007_remove_actainicio_numero_actainicio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='actainicio',
            name='fecha',
            field=models.DateField(max_length=300, verbose_name='Fecha de acta de inicio'),
        ),
        migrations.AlterField(
            model_name='rp',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número del RP'),
        ),
    ]
