# Generated by Django 5.2.5 on 2025-08-17 01:33

from django.db import migrations


def fix_supervisor_reference(apps, schema_editor):
    """
    Corrige la referencia de la clave foránea supervisor_id en la tabla contrato
    para que apunte correctamente a gestion_supervisor_supervisor
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Eliminar la restricción de clave foránea existente si existe
        cursor.execute("""
            PRAGMA foreign_keys=OFF;
        """)
        
        # Recrear la tabla con la referencia correcta
        cursor.execute("""
            CREATE TABLE "gestion_usuarios_contrato_new" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "numero_pagos" integer NOT NULL,
                "supervisor_id" integer NOT NULL REFERENCES "gestion_supervisor_supervisor" ("cedula") DEFERRABLE INITIALLY DEFERRED,
                "numero_proceso" varchar(100),
                "archivo" varchar(100) NOT NULL,
                "fecha_creacion" datetime NOT NULL,
                "fecha_actualizacion" datetime NOT NULL
            )
        """)
        
        # Copiar datos existentes si los hay
        cursor.execute("""
            INSERT INTO "gestion_usuarios_contrato_new" 
            SELECT * FROM "gestion_usuarios_contrato"
        """)
        
        # Eliminar tabla antigua y renombrar la nueva
        cursor.execute("DROP TABLE \"gestion_usuarios_contrato\"")
        cursor.execute("ALTER TABLE \"gestion_usuarios_contrato_new\" RENAME TO \"gestion_usuarios_contrato\"")
        
        # Crear índice para la clave foránea
        cursor.execute("""
            CREATE INDEX "gestion_usuarios_contrato_supervisor_id_idx" 
            ON "gestion_usuarios_contrato" ("supervisor_id")
        """)
        
        # Reactivar las claves foráneas
        cursor.execute("""
            PRAGMA foreign_keys=ON;
        """)


def reverse_fix_supervisor_reference(apps, schema_editor):
    """
    Función de reversión - no implementada
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0008_auto_20250816_2028'),
        ('gestion_supervisor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            fix_supervisor_reference,
            reverse_fix_supervisor_reference,
        ),
    ]
