# Generated by Django 5.2.5 on 2025-08-14 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0008_rp_id_alter_actainicio_fecha_alter_rp_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numeroproceso',
            field=models.CharField(max_length=200, verbose_name='Número del proceso'),
        ),
        migrations.CreateModel(
            name='planilla',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de la planilla')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago de la planilla')),
                ('periodo', models.CharField(max_length=20, verbose_name='Periodo de la planilla')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total de la planilla')),
                ('nombre_pension', models.CharField(max_length=150, verbose_name='Entidad de pensión')),
                ('valor_pension', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de pensión')),
                ('nombre_salud', models.CharField(max_length=150, verbose_name='Entidad de salud')),
                ('valor_salud', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de salud')),
                ('nombre_arl', models.CharField(max_length=150, verbose_name='Entidad ARL')),
                ('valor_arl', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de ARL')),
                ('archivo', models.FileField(default='NO CARGADO', upload_to='pdfs/', verbose_name='Archivo de soporte')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario', verbose_name='Usuario asociado')),
            ],
        ),
    ]
