# Generated by Django 5.2.5 on 2025-08-14 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0009_alter_contrato_numeroproceso_planilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='ibc',
            field=models.CharField(default=datetime.datetime(2025, 8, 14, 17, 3, 14, 585967, tzinfo=datetime.timezone.utc), max_length=200, verbose_name='IBC de la planilla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planilla',
            name='periodo',
            field=models.CharField(choices=[('01', 'ENERO'), ('02', 'FEBRERO'), ('03', 'MARZO'), ('04', 'ABRIL'), ('05', 'MAYO'), ('06', 'JUNIO'), ('07', 'JULIO'), ('08', 'AGOSTO'), ('09', 'SEPTIEMBRE'), ('10', 'OCTUBRE'), ('11', 'NOVIEMBRE'), ('12', 'DICIEMBRE')], max_length=2, verbose_name='Mes de pago'),
        ),
    ]
