# Generated by Django 5.2.5 on 2025-08-17 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0009_auto_20250816_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='rp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.rp', verbose_name='RP asociado'),
        ),
    ]
