# Generated by Django 5.2.5 on 2025-08-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0010_contrato_rp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Archivo adjunto'),
        ),
    ]
