# Generated by Django 5.2.5 on 2025-08-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0011_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='firma',
            field=models.ImageField(default='imgs/sinfoto.jpeg', upload_to='imgs/firmas'),
        ),
    ]
