# Generated by Django 5.2.5 on 2025-08-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micuenta', '0002_radicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado del radicado'),
        ),
    ]
