# Generated by Django 5.2.5 on 2025-08-14 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micuenta', '0003_radicado_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentabancaria',
            fields=[
                ('numero', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Numero de cuenta bancaria')),
                ('tipocuenta', models.CharField(choices=[('AHO', 'CUENTA DE AHORROS'), ('COR', 'CUENTA CORRIENTE'), ('CRED', 'CUENTA DE CREDITO')], max_length=100, verbose_name='Tipo de cuenta bancaria')),
                ('nombrecb', models.CharField(max_length=40, verbose_name='Nombre de cuenta bancaria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario autenticado')),
            ],
        ),
    ]
