# Generated by Django 5.2.5 on 2025-08-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_rp_usuario_firma_documento_planilla_delete_contrato'),
        ('micuenta', '0004_cuentabancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario', verbose_name='Usuario asociado'),
        ),
        migrations.AlterField(
            model_name='radicado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario', verbose_name='Usuario asociado'),
        ),
    ]
