# Generated by Django 5.2.5 on 2025-08-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40, verbose_name='Nombre de usuario')),
                ('referencia', models.CharField(default='Recordatorio de citas', max_length=60, verbose_name='Referencia')),
                ('email', models.EmailField(max_length=40, verbose_name='Correo destinatario')),
                ('enviado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mensaje', models.CharField(max_length=300, verbose_name='Mensaje')),
            ],
        ),
    ]
